# Generated by Django 3.2.8 on 2023-08-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
    ]
