# Generated by Django 3.2.8 on 2023-08-18 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('year_article', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('type', models.CharField(choices=[('Records', 'Disk'), ('Clothing', 'Clothes'), ('Posters', 'Poster'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
            ],
        ),
    ]
