# Generated by Django 3.2.8 on 2023-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_band_like_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='biography',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
